### ISSUE TITLE
Cannot save PDF files

### ISSUE THREAD

**Issue by mattwoPhre** [hearsid/ng-html-to-pdf-save#1]
HI devs!!! :) i would like to ask you one thing: i cannot save my html in a pdf with this library. I think that there's a problem in createPDF() function, because after that getCanvas() function is done, the promise in then is broken because it doesn't create pdf or execute the function inside .then either.

UPDATE: i've modified a little bit the library and put error condition in resolve, so it logs me "CanvasRenderer is not defined". I googled a bit and i've found that maybe it's a jspdf version problem.

UPDATE 2: i have to put jspdf.debug.js and all works! but there's problem with pdfs with more than one page and quality. If you don't mind, can i make pull request? :)

**Comment by hearsid** [comment]
@mattwoPhre Sorry for the late reply.
Yes, please make the pull request 👍

**Comment by hearsid** [comment]
Have fixed the same in PR https://github.com/hearsid/ng-html-to-pdf-save/pull/2
