### ISSUE TITLE
Multi-page (first page: correct, others pages: blank)

### ISSUE THREAD

**Issue by adairborba** [hearsid/ng-html-to-pdf-save#14]
On more than one page, only the first one has information, the next, are left blank.

**Comment by hearsid** [comment]
@vijaydogra The PR you created (https://github.com/hearsid/ng-html-to-pdf-save/pull/10) was supposed to solve this issue, right? An explanation or help in the same will be appreciated.

**Comment by vijaydogra** [comment]
@adairborba  Can you upload your test program please for me to test? I am currently not able to reproduce here.

**Comment by adairborba** [comment]
@vijaydogra  I did a series of tests, and I understood that a CSS definition of the bootstrap framework was creating the bug.
I removed the css block, and it is functional.
Now, just find a better way to crop the images.
