### ISSUE TITLE
Issues when export table to PDF

### ISSUE THREAD

**Issue by gerson23** [hearsid/ng-html-to-pdf-save#5]
When I try to create a PDF from a bootstrap table, it does create the PDF file. However, I'm getting three issues:

1. The background color of the table is black (on my browser is white). I wonder if this can be an issue with Bootstrap's CSS and html2canvas too.

2. Table's length is greater than 1 page, but instead of creating another page, it cut's off the bottom of the table.

3. Also it does not respect the pdf-name tag, the downloaded file is named "chart-reports.pdf".

My jade's template looks like:

        button(pdf-save-button="main", pdf-name="test.pdf", class="btn btn-primary") download
        div(pdf-save-content="main")
            table(class="table table-bordered table-condensed")
                tbody
                    tr
                        td(rowspan="4", colspan="2")
                            img(class="center-block", src="/images/logo.png")
                        td(colspan="4") Report
                    tr
                        td Col 1
                        td Col 2
                        td(colspan="2") Col 3

And the javascript:

        script(src='bower_components/angular/angular.min.js')
        script(src='bower_components/moment/moment.js')
        script(src='bower_components/angular-moment/angular-moment.min.js')
        script(src='bower_components/angular-animate/angular-animate.min.js')
        script(src='bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js')
        script(src='bower_components/jquery/dist/jquery.min.js')
        script(src='https://cdn.rawgit.com/niklasvh/html2canvas/0.5.0-alpha2/dist/html2canvas.min.js')
        script(src='bower_components/jsPDF/dist/jspdf.debug.js')
        script(src='bower_components/angular-save-html-to-pdf/dist/saveHtmlToPdf.min.js')

**Comment by hearsid** [comment]
@gerson23 The 3rd issue has got solved and merged in this PR https://github.com/hearsid/ng-html-to-pdf-save/pull/6.

**Comment by mattijswilms** [comment]
Facing the second issue

**Comment by vijaydogra** [comment]
Multiple page support is missing I guess

**Comment by vijaydogra** [comment]
I had actually done a research and copied/pasted solution from stackoverflow. If anybody is interested, the solution is here, will try to pull the repo and make the changes, however I have never done this thing before - 

http://stackoverflow.com/questions/19272933/jspdf-multi-page-pdf-with-html-renderrer

**Comment by hearsid** [comment]
@vijaydogra Please check if the solution you got on stackoverflow is working and go ahead with creating the PR.

**Comment by hearsid** [comment]
@vijaydogra The code you added in the above PR (https://github.com/hearsid/ng-html-to-pdf-save/pull/7)  was creating blank PDF files, please check if the code is working before creating a PR, if you need any help please feel free to ping me.
<img width="856" alt="screen shot 2017-01-12 at 8 39 43 pm" src="https://cloud.githubusercontent.com/assets/3892451/21895291/250b3f58-d908-11e6-8c49-af1c2199cd80.png">
[hello.pdf](https://github.com/hearsid/ng-html-to-pdf-save/files/702062/hello.pdf)

**Comment by vijaydogra** [comment]
I will fix this issue

**Comment by vijaydogra** [comment]
Pull request created

**Comment by hearsid** [comment]
@vijaydogra  Your PR (https://github.com/hearsid/ng-html-to-pdf-save/pull/10) has got merged, I guess the multiple page support should work now.

**Comment by gerson23** [comment]
Thanks guys. I tested with the latest version and the issues are gone. I think we can close this.
